# Generated by Django 5.1.2 on 2024-11-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mypost",
            "0003_alter_post_options_board_created_at_board_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tech", "Technology"),
                            ("life", "Life"),
                            ("news", "News"),
                        ],
                        default="tech",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Board",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
